### ISSUE TITLE
Relations don't exist

### ISSUE THREAD

**Issue by tonylomax** [fac19/week7-BGJK#25]
I have this error ```error : relation "users" does not exist``` when trying to hit certain endpoints, specifically the createuser and login endpoints which makes it sorta difficult to test. It's great that you have some authentication taking place though!

**Comment by tonylomax** [comment]
I've played around with it some more and stopped my prettier from changing the single quotes to double  but still have this issue. Looks like your build file is set up right and the queries work in psql, google suggests this could be a few different things but there's nothing I can get working. This may work locally on your machines but obviously when you host it you'll want to check this issue doesn't persist. 

(There's a chance this is of course all my fault and I'm doing something wrong, if so please do tell me so I can a) learn and b) have an excuse to avoid work 😅

**Comment by oliverjam** [comment]
It looks like the Heroku database was never initialised with any tables. Did you run your `init.sql` script while connected to the Heroku DB?

**Comment by VatsKan** [comment]
hey oli we tried doing this but didnt seem to work/dont know how to do this the right way. any help would be grateful

**Comment by oliverjam** [comment]
I can jump in a breakout room if you like

**Comment by glrta** [comment]
Maria helped us!! Thank you, Oli. All good now :)

**Comment by glrta** [comment]
Maria helped us!! Thank you, Oli. All good now :)

**Comment by oliverjam** [comment]
Awesome. Just to satisfy my curiosity, what was the problem?
