### ISSUE TITLE
Create user function - ERROR HANDLING 

### ISSUE THREAD

**Issue by tacotoemeck** [fac19/week7-BGJK#32]
Currently your application crashes when user tries to create a new user with an existing username. Request "hangs" for a while then crashes and only logs in the error in the console. It would be great for a user to receive "something" back even if it's an error. This can be fixed by adding an extra .catch at the end of your function:

```javascript=
function createUser(req, res, next) {
  const username = req.body.username;
  const password = req.body.password;

  bcrypt
    .genSalt(10)
    .then((salt) => bcrypt.hash(password, salt))
    .then((hash) => {
      model
        .addUser(username, hash)
        .then((userId) => {
          return model.getUser(userId);
        })
        .then((result) => {
          const token = jwt.sign({ user: result.id }, SECRET, {
            expiresIn: "1h",
          });
          result.token = token;
          res.status(201).send(result);
        })
        .catch(next); // this is moved <=== FIX IS HERE
    })
    .catch(console.error); // this is new <=== FIX IS HERE
}
```
Using this will allow a user to see a message such as this:

"error : duplicate key value violates unique constraint"

**Comment by CampbellDocherty** [comment]
Thank you for the helpful feedback!
